export default {
    lang: 'zh-CN',
    languages: {
        'zh-CN': {
            wangEditor: {
                插入: '插入',
                默认: '默认',
                创建: '创建',
                修改: '修改',
                如: '如',
                请输入正文: '请输入正文',
                menus: {
                    dropListMenu: {
                        设置标题: '设置标题',
                        背景颜色: '背景颜色',
                        文字颜色: '文字颜色',
                        设置字号: '设置字号',
                        设置字体: '设置字体',
                        设置缩进: '设置缩进',
                        对齐方式: '对齐方式',
                        设置行高: '设置行高',
                        序列: '序列',
                        head: {
                            正文: '正文',
                        },
                        indent: {
                            增加缩进: '增加缩进',
                            减少缩进: '减少缩进',
                        },
                        justify: {
                            靠左: '靠左',
                            居中: '居中',
                            靠右: '靠右',
                        },
                        list: {
                            无序列表: '无序列表',
                            有序列表: '有序列表',
                        },
                    },
                    panelMenus: {
                        emoticon: {
                            默认: '默认',
                            新浪: '新浪',
                            emoji: 'emoji',
                            手势: '手势',
                        },
                        image: {
                            图片链接: '图片链接',
                            上传图片: '上传图片',
                            网络图片: '网络图片',
                        },
                        link: {
                            链接: '链接',
                            链接文字: '链接文字',
                            删除链接: '删除链接',
                            查看链接: '查看链接',
                        },
                        video: {
                            插入视频: '插入视频',
                        },
                        table: {
                            行: '行',
                            列: '列',
                            的: '的',
                            表格: '表格',
                            插入表格: '插入表格',
                        },
                        code: {
                            代码: '代码',
                        },
                    },
                },
                validate: {
                    张: '张',
                    大于: '大于',
                    不是: '不是',
                    图片: '图片',
                    验证: '验证',
                    上传: '上传',
                    下载: '下载',
                    超时: '超时',
                    失败: '失败',
                    错误: '错误',
                    链接: '链接',
                    未通过: '未通过',
                    插入图片: '插入图片',
                    一次最多: '一次最多',
                    发生错误: '发生错误',
                    返回结果: '返回结果',
                    服务器返回状态: '服务器返回状态',
                    请替换为支持的图片类型: '请替换为支持的图片类型',
                    您插入的网络图片无法识别: '您插入的网络图片无法识别',
                    您刚才插入的图片链接未通过编辑器校验: '您刚才插入的图片链接未通过编辑器校验',
                },
            },
        },
        en: {
            wangEditor: {
                插入: 'insert',
                默认: 'default',
                创建: 'create',
                修改: 'edit',
                如: 'like',
                请输入正文: 'please enter the text',
                menus: {
                    dropListMenu: {
                        设置标题: 'title',
                        背景颜色: 'background',
                        文字颜色: 'font color',
                        设置字号: 'font size',
                        设置字体: 'font family',
                        设置缩进: 'indent',
                        对齐方式: 'align',
                        设置行高: 'line heihgt',
                        序列: 'list',
                        head: {
                            正文: 'text',
                        },
                        indent: {
                            增加缩进: 'indent',
                            减少缩进: 'outdent',
                        },
                        justify: {
                            靠左: 'left',
                            居中: 'center',
                            靠右: 'right',
                        },
                        list: {
                            无序列表: 'unordered',
                            有序列表: 'ordered',
                        },
                    },
                    panelMenus: {
                        emoticon: {
                            默认: 'default',
                            新浪: 'sina',
                            emoji: 'emoji',
                            手势: 'gesture',
                        },
                        image: {
                            图片链接: 'image link',
                            上传图片: 'upload image',
                            网络图片: 'network image',
                        },
                        link: {
                            链接: 'link',
                            链接文字: 'link text',
                            删除链接: 'delete',
                            查看链接: 'view',
                        },
                        video: {
                            插入视频: 'insert video',
                        },
                        table: {
                            行: 'row',
                            列: 'column',
                            的: ' ',
                            表格: 'table',
                            插入表格: 'insert table',
                        },
                        code: {
                            插入代码: 'insert code',
                        },
                    },
                },
                validate: {
                    张: 'zhang ',
                    大于: 'greater than ',
                    不是: 'no ',
                    图片: 'image ',
                    验证: 'validate ',
                    上传: 'upload ',
                    下载: 'download ',
                    超时: 'timeout',
                    失败: 'fail ',
                    错误: 'error ',
                    链接: 'link ',
                    未通过: 'failed ',
                    插入图片: 'insert image ',
                    一次最多: 'most ',
                    发生错误: 'error ',
                    返回结果: 'return results ',
                    服务器返回状态: 'server return status ',
                    请替换为支持的图片类型: 'please replace with a supported image type',
                    您插入的网络图片无法识别: 'the network picture you inserted is not recognized',
                    您刚才插入的图片链接未通过编辑器校验:
                        'the image link you just inserted did not pass the editor verification',
                },
            },
        },
    },
}
